### ISSUE TITLE
Create Hobby Tags Backend

### ISSUE THREAD

**Issue by KyoshiNoda** [KyoshiNoda/ScheduleFinder#240]
### **Description** 
- As a part of the the new `User Profile` feature we were discussing, we need to implement a `Tag` property. 
- Each user can select hobbies and other things they like, each hobby can be represented by a generic `Tag` with a color.
- The `Tag` property will be used for #180 and #181 
- I believe these tags should replicate the Labels on Github and have a slightly transparent color to them.
- For these feature, you can either implement the backend design and write boiler code for it.

### **Acceptance Criteria**
- loose requirements for this story as its in early development. Prioritize good design over nitty picky implementation.
- Have a new endpoint defined in either `UserRoute` or create a new `Route`

**Comment by KyoshiNoda** [comment]
![Image](https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/9431e670-10ab-48b9-be04-876ea3257a87)

**Comment by CDDR1** [comment]
> @CDDR1 What do you think of this design?
> 
> The only downfall for this approach would be an expensive collection `Tag` as there will be many hobbies/tags people can be into. However it allows easier filter with a method like GET `api/users/tag` and that will return all users with with matching hobbies of the current user signed in.
> 
> ### Questions
> 1. Should we have `PATCH` or `DELETE` operations?
>    
>    * I strongly believe we shouldn't because it doesn't make sense to edit or delete a valid tag as other users will be able to use those tags.
>    * Alternatively, we should just check new tags if they are valid or not and keep them for other users to use it.
> 2. Are we allowing users to select their preset colors for each Tag?
>    
>    * If we allow users to select their own colors, this would mean we have to change the `hobbies` in the `User` schema and the hobbies array would be an `Tag` type with color, name.
>    * Else we can just have random preset colors and just store them in the backend for everyone to use.
> 
> ![Image](https://private-user-images.githubusercontent.com/62672803/290733727-9431e670-10ab-48b9-be04-876ea3257a87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTgxOTcsIm5iZiI6MTcwMjY1Nzg5NywicGF0aCI6Ii82MjY3MjgwMy8yOTA3MzM3MjctOTQzMWU2NzAtMTBhYi00OGI5LWJlMDQtODc2ZWEzMjU3YTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE2MzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNDg2ODRkYTE5MjFiZDdhZGNkNTM0MjM4ZDQxMzc5NDczNTJjZDEwNTJiMjNhYjMxYjljMWI0ZjlkOGY2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zwEW5tZrPyD_m8O5IWPTI3EB6HOtjtlk4fnlMj7ybMs)

Notes:
- I think we should only include a set of tags that the users can choose from. We can try to cover all the popular activities/hobbies that people are into. I don't think the benefits of allowing users to create their own tags are worth the extra complexity that this would require, because if a user feels the need to create their own tag instead of choosing one of the default ones, the tag they would be creating is probably a very obscure hobby that not many other people have, so if we want to match people that have similar hobbies, this wouldn't really be too beneficial. I don't know if that makes sense, I can clarify that if you want me to. 

- If we decide to only have a default set of tags, I agree that we wouldn't need `DELETE` nor `PATCH` operations for the tags themselves. We would need a `PATCH` endpoint though for when a user wants to add or remove a tag, and potentially a `PUT` endpoint if they want to remove all their tags at once, which would basically be replacing the `hobbies` array for an empty one for the given user. I would also push for changing the name of the tag collection to something like `hobby_tag` and same thing for the hobbies array in the user collection; change it for something like `hobbies_tags`.

- I'm not sure if we would need colors at all, we could just keep all the tags a same color. I think this would look cleaner in a user's profile page for example. We could choose one of the available colors from flowbite's [badge component](https://flowbite.com/docs/components/badge/).
